window.RC_CONFIG = window.RC_CONFIG || {};
window.RC_CONFIG.SUPABASE_URL = "COLE_AQUI_A_URL_REAL_QUE_VOCE_COPIOU_DO_SUPABASE";
window.RC_CONFIG.SUPABASE_ANON_KEY = "COLE_AQUI_A_CHAVE_ANON_REAL_QUE_VOCE_COPIOU_DO_SUPABASE";
window.SUPABASE_URL = window.RC_CONFIG.SUPABASE_URL;
window.SUPABASE_ANON_KEY = window.RC_CONFIG.SUPABASE_ANON_KEY;
